-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/labki_content_repo (
  content_repo_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  content_repo_url VARCHAR(255) NOT NULL,
  default_ref VARCHAR(100) DEFAULT 'main',
  bare_path VARCHAR(500) DEFAULT NULL,
  last_fetched BLOB DEFAULT NULL,
  created_at BLOB NOT NULL,
  updated_at BLOB NOT NULL
);

CREATE UNIQUE INDEX content_repo_url_unique ON /*_*/labki_content_repo (content_repo_url);

CREATE INDEX idx_labki_repo_url ON /*_*/labki_content_repo (content_repo_url);

CREATE INDEX idx_labki_repo_last_fetched ON /*_*/labki_content_repo (last_fetched);


CREATE TABLE /*_*/labki_content_ref (
  content_ref_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  content_repo_id INTEGER UNSIGNED NOT NULL,
  source_ref VARCHAR(255) NOT NULL,
  content_ref_name VARCHAR(255) DEFAULT NULL,
  last_commit VARCHAR(40) DEFAULT NULL,
  manifest_hash VARCHAR(64) DEFAULT NULL,
  manifest_last_parsed BLOB DEFAULT NULL,
  worktree_path VARCHAR(500) DEFAULT NULL,
  created_at BLOB NOT NULL,
  updated_at BLOB NOT NULL
);

CREATE UNIQUE INDEX content_repo_ref_unique ON /*_*/labki_content_ref (content_repo_id, source_ref);

CREATE INDEX idx_labki_ref_repo ON /*_*/labki_content_ref (content_repo_id);

CREATE INDEX idx_labki_ref_name ON /*_*/labki_content_ref (content_ref_name);

CREATE INDEX idx_labki_ref_source_ref ON /*_*/labki_content_ref (source_ref);

CREATE INDEX idx_labki_ref_last_commit ON /*_*/labki_content_ref (last_commit);

CREATE INDEX idx_labki_ref_manifest_hash ON /*_*/labki_content_ref (manifest_hash);


CREATE TABLE /*_*/labki_pack (
  pack_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  content_ref_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  version VARCHAR(50) DEFAULT NULL,
  source_commit VARCHAR(40) DEFAULT NULL,
  installed_at BLOB DEFAULT NULL,
  installed_by INTEGER UNSIGNED DEFAULT NULL,
  updated_at BLOB DEFAULT NULL,
  STATUS VARCHAR(20) DEFAULT 'installed'
);

CREATE UNIQUE INDEX content_ref_name_unique ON /*_*/labki_pack (content_ref_id, name);

CREATE INDEX idx_labki_pack_ref ON /*_*/labki_pack (content_ref_id);


CREATE TABLE /*_*/labki_page (
  page_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pack_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  final_title VARCHAR(255) NOT NULL,
  page_namespace INTEGER NOT NULL,
  wiki_page_id INTEGER UNSIGNED DEFAULT NULL,
  last_rev_id INTEGER UNSIGNED DEFAULT NULL,
  content_hash VARCHAR(64) DEFAULT NULL,
  created_at BLOB DEFAULT NULL,
  updated_at BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX pack_name_unique ON /*_*/labki_page (pack_id, name);

CREATE UNIQUE INDEX pack_final_title_unique ON /*_*/labki_page (pack_id, final_title);

CREATE INDEX idx_labki_page_pack ON /*_*/labki_page (pack_id);

CREATE INDEX idx_labki_page_final_title ON /*_*/labki_page (final_title);

CREATE INDEX idx_labki_page_wiki_page_id ON /*_*/labki_page (wiki_page_id);


CREATE TABLE /*_*/labki_pack_dependency (
  pack_id INTEGER UNSIGNED NOT NULL,
  depends_on_pack_id INTEGER UNSIGNED NOT NULL,
  created_at BLOB NOT NULL,
  PRIMARY KEY(pack_id, depends_on_pack_id)
);

CREATE INDEX idx_labki_pack_dependency_depends_on ON /*_*/labki_pack_dependency (depends_on_pack_id);


CREATE TABLE /*_*/labki_operations (
  operation_id VARCHAR(100) NOT NULL,
  operation_type VARCHAR(50) NOT NULL,
  STATUS VARCHAR(20) DEFAULT 'queued' NOT NULL,
  progress INTEGER UNSIGNED DEFAULT 0,
  message VARCHAR(500) DEFAULT '',
  result_data BLOB DEFAULT NULL,
  user_id INTEGER UNSIGNED DEFAULT 0,
  created_at BLOB NOT NULL,
  started_at BLOB DEFAULT NULL,
  updated_at BLOB NOT NULL,
  PRIMARY KEY(operation_id)
);

CREATE INDEX idx_labki_operations_status ON /*_*/labki_operations (STATUS);

CREATE INDEX idx_labki_operations_type ON /*_*/labki_operations (operation_type);

CREATE INDEX idx_labki_operations_user ON /*_*/labki_operations (user_id);

CREATE INDEX idx_labki_operations_updated ON /*_*/labki_operations (updated_at);
