-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/labki_content_repo (
  content_repo_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  content_repo_url VARCHAR(255) NOT NULL,
  default_ref VARCHAR(100) DEFAULT 'main',
  bare_path VARCHAR(500) DEFAULT NULL,
  last_fetched BINARY(14) DEFAULT NULL,
  created_at BINARY(14) NOT NULL,
  updated_at BINARY(14) NOT NULL,
  UNIQUE INDEX content_repo_url_unique (content_repo_url),
  INDEX idx_labki_repo_url (content_repo_url),
  INDEX idx_labki_repo_last_fetched (last_fetched),
  PRIMARY KEY(content_repo_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/labki_content_ref (
  content_ref_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  content_repo_id INT UNSIGNED NOT NULL,
  source_ref VARCHAR(255) NOT NULL,
  content_ref_name VARCHAR(255) DEFAULT NULL,
  last_commit VARCHAR(40) DEFAULT NULL,
  manifest_hash VARCHAR(64) DEFAULT NULL,
  manifest_last_parsed BINARY(14) DEFAULT NULL,
  worktree_path VARCHAR(500) DEFAULT NULL,
  created_at BINARY(14) NOT NULL,
  updated_at BINARY(14) NOT NULL,
  UNIQUE INDEX content_repo_ref_unique (content_repo_id, source_ref),
  INDEX idx_labki_ref_repo (content_repo_id),
  INDEX idx_labki_ref_name (content_ref_name),
  INDEX idx_labki_ref_source_ref (source_ref),
  INDEX idx_labki_ref_last_commit (last_commit),
  INDEX idx_labki_ref_manifest_hash (manifest_hash),
  PRIMARY KEY(content_ref_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/labki_pack (
  pack_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  content_ref_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  version VARCHAR(50) DEFAULT NULL,
  source_commit VARCHAR(40) DEFAULT NULL,
  installed_at BINARY(14) DEFAULT NULL,
  installed_by INT UNSIGNED DEFAULT NULL,
  updated_at BINARY(14) DEFAULT NULL,
  STATUS VARCHAR(20) DEFAULT 'installed',
  UNIQUE INDEX content_ref_name_unique (content_ref_id, name),
  INDEX idx_labki_pack_ref (content_ref_id),
  PRIMARY KEY(pack_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/labki_page (
  page_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pack_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  final_title VARCHAR(255) NOT NULL,
  page_namespace INT NOT NULL,
  wiki_page_id INT UNSIGNED DEFAULT NULL,
  last_rev_id INT UNSIGNED DEFAULT NULL,
  content_hash VARCHAR(64) DEFAULT NULL,
  created_at BINARY(14) DEFAULT NULL,
  updated_at BINARY(14) DEFAULT NULL,
  UNIQUE INDEX pack_name_unique (pack_id, name),
  UNIQUE INDEX pack_final_title_unique (pack_id, final_title),
  INDEX idx_labki_page_pack (pack_id),
  INDEX idx_labki_page_final_title (final_title),
  INDEX idx_labki_page_wiki_page_id (wiki_page_id),
  PRIMARY KEY(page_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/labki_pack_dependency (
  pack_id INT UNSIGNED NOT NULL,
  depends_on_pack_id INT UNSIGNED NOT NULL,
  created_at BINARY(14) NOT NULL,
  INDEX idx_labki_pack_dependency_depends_on (depends_on_pack_id),
  PRIMARY KEY(pack_id, depends_on_pack_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/labki_operations (
  operation_id VARCHAR(100) NOT NULL,
  operation_type VARCHAR(50) NOT NULL,
  STATUS VARCHAR(20) DEFAULT 'queued' NOT NULL,
  progress INT UNSIGNED DEFAULT 0,
  message VARCHAR(500) DEFAULT '',
  result_data BLOB DEFAULT NULL,
  user_id INT UNSIGNED DEFAULT 0,
  created_at BINARY(14) NOT NULL,
  started_at BINARY(14) DEFAULT NULL,
  updated_at BINARY(14) NOT NULL,
  INDEX idx_labki_operations_status (STATUS),
  INDEX idx_labki_operations_type (operation_type),
  INDEX idx_labki_operations_user (user_id),
  INDEX idx_labki_operations_updated (updated_at),
  PRIMARY KEY(operation_id)
) /*$wgDBTableOptions*/;
